create table order_mes_box
(
    id          bigint generated by default as identity,
    item_code   varchar(50) unique,
    box_1       varchar(50),
    box_2       varchar(50),
    box_3       varchar(50),
    box_4       varchar(50),
    box_5       varchar(50),
    w_qty       int,
    p_qty       int,
    created_at  timestamp not null,
    modified_at timestamp,
    primary key (id)
);


create table order_mes_stock
(
    id          bigint generated by default as identity,
    factory     varchar(10),
    item_code   varchar(50),
    qty         int,
    created_at  timestamp not null,
    modified_at timestamp,
    primary key (id)
);
create unique index unq_factory_item_code on order_mes_stock (factory, item_code);

create table order_mes_stock_outbound
(
    id            bigint generated by default as identity,
    item_code     varchar(50) not null,
    outbound_date date        not null,
    out_qty       int,
    created_at    timestamp   not null,
    modified_at   timestamp,
    primary key (id)
);

create unique index unq_item_code_outbound_date on order_mes_stock_outbound (item_code, outbound_date);


create table order_car
(
    id          bigint generated by default as identity,
    category    varchar(10) not null,
    supplier    varchar(50),
    item_name   varchar(50),
    alc         varchar(15) not null,
    item_code   varchar(50) not null,
    remark      text,
    t_time      varchar(20),
    space       int,
    result      int         not null,
    line        int         not null,
    yra         int         not null,
    in_house    int         not null,
    inspection  int         not null,
    ct          int         not null,
    long_term   int         not null,
    oem         int         not null,
    space1      int,
    space2      int,
    space3      int,
    space4      int,
    space5      int,
    space6      int,
    space7      int,
    space8      int,
    space9      int,
    space10     int,
    space11     int,
    space12     int,
    space13     int,
    d           int,
    d_plus1     int,
    d_plus2     int,
    d_plus3     int,
    d_plus4     int,
    d_plus5     int,
    d_plus6     int,
    d_plus7     int,
    d_plus8     int,
    d_plus9     int,
    d_plus10    int,
    d_plus11    int,
    d_plus12    int,
    d_plus13    int,
    d_plus14    int,
    d_plus15    int,
    d_plus16    int,
    d_plus17    int,
    d_plus18    int,
    d_plus19    int,
    d_plus20    int,
    rem         int,
    ct_location varchar(100),
    upload_date date        not null,
    created_at  timestamp   not null,
    modified_at timestamp,
    primary key (id)
);

create unique index unq_category_item_code_upload_date on order_car (category, item_code, upload_date);

CREATE TABLE order_mes_stock_box
(
    item_code   VARCHAR(255) PRIMARY KEY,
    box1        INT,
    box2        INT,
    box3        INT,
    box4        INT,
    box5        INT,
    box6        INT,
    box7        INT,
    box8        INT,
    box9        INT,
    box10       INT,
    box11       INT,
    box12       INT,
    box13       INT,
    box14       INT,
    box15       INT,
    box16       INT,
    box17       INT,
    box18       INT,
    box19       INT,
    box20       INT,
    box21       INT,
    box22       INT,
    box23       INT,
    box24       INT,
    box25       INT,
    box26       INT,
    box27       INT,
    box28       INT,
    box29       INT,
    box30       INT,
    created_at  timestamp not null,
    modified_at timestamp
);

CREATE TABLE order_second_outbound
(
    item_code   varchar(255),
    qty         INT,
    upload_date DATE,
    created_at  timestamp not null,
    modified_at timestamp,
    PRIMARY KEY (item_code, upload_date)
);





