CREATE TABLE order_ops_plan_raw
(
    id           bigint generated by default as identity,
    st_date      date        not null,
    car_props    varchar(20) not null,
    region       varchar(20) not null,
    nation       varchar(20) not null,
    door_type    varchar(20) not null,
    engine_capa  varchar(20) not null,
    transmission varchar(20) not null,
    mc           varchar(20) not null,
    st_month1    int,
    st_month2    int,
    st_month3    int,
    st_month4    int,
    st_month5    int,
    etc          varchar,
    customer     varchar(20) not null,
    responder    varchar(10) not null,
    upload_date  date        not null,
    created_at   timestamp   not null,
    modified_at  timestamp,
    primary key (id)
)