CREATE TABLE order_ops_plan_raw_agg
(
    id           bigint generated by default as identity,
    st_date      date        not null,
    car_props    varchar(20) not null,
    group_props  varchar(20) not null,
    st_month1_agg    int,
    st_month2_agg   int,
    st_month3_agg    int,
    st_month4_agg    int,
    st_month5_agg    int,
    created_at   timestamp   not null,
    modified_at  timestamp,
    primary key (id)
)