CREATE TABLE order_ops_plan_past_mon_agg
(
    id           bigint generated by default as identity,
    st_date      date        not null,
    from_date    date        not null ,
    to_date      date        not null ,
    car_item     varchar(30) not null,
    part_no      varchar(30) not null,
    door_type    varchar(20) not null,
    region       varchar(20) not null,
    d_plus_total int not null,
    responder    varchar(20) not null ,
    created_at   timestamp   not null,
    modified_at  timestamp,
    primary key (id)
)